### PR TITLE
fix file deletion and rename in root dir for 8.7.16

### PR DESCRIPTION
**Pull request by dni**
suggested by Nicole Cordes

ich hab gleichzeit aber auch nen core-patch, wenn du den testen magst?!
kannst dir aussuchen: extension ändern, core ändern, oder beides :slightly_smiling_face:
genau, in \AUS\AusDriverAmazonS3\Driver\AmazonS3Driver
https://review.typo3.org/57120
release: wenn ich das richtig sehe, ist das nächste release am 21.8 geplant

### CODE REVIEW

**Comment by Lagerregal** [comment]
Code style have to be fixed (see travis):


FILE: ...rsundsehr/aus_driver_amazon_s3/Classes/Driver/AmazonS3Driver.php

FOUND 7 ERRORS AFFECTING 7 LINES

 1384 | ERROR | [x] Line indented incorrectly; expected 4 spaces, found 3
 1385 | ERROR | [x] Line indented incorrectly; expected at least 4 spaces, found 3
 1386 | ERROR | [x] Line indented incorrectly; expected at least 8 spaces, found 7
 1387 | ERROR | [x] Line indented incorrectly; expected 8 spaces, found 7
 1388 | ERROR | [x] Line indented incorrectly; expected at least 12 spaces, found 11
 1389 | ERROR | [x] Line indented incorrectly; expected 8 spaces, found 7
 1390 | ERROR | [x] Line indented incorrectly; expected 4 spaces, found 3

**Comment by c0defre4k** [comment]
Any updates on this? This issue exists since almost 3 months!

**Comment by dni** [comment]
i think this should be fixed with 8.7.19 was a 8.6.16 specific issue, the PR should be obsolete now, but i have not tested it in depth.

**Comment by c0defre4k** [comment]
I have 8.7.19 in my projects and the problem still persists. Although I don't know if there is another problem causing the same issue.

**Comment by dni** [comment]
ok, does my PR fix your issue? then ill try to fix the codecheck is submit it again.

**Comment by c0defre4k** [comment]
Just tested you fix. It worked for me. 👍

**Comment by dni** [comment]
ok, fixed it should be ready to merge now.

**Pull request closed without merging**
